server:
  port: 8881
rpc:
  client:
    load-balance: random
    serialization: PROTOSTUFF
    transport: netty
    registry: zookeeper
    registry-addr: 192.168.199.132:2182
    timeout: 5000

# 设置控制台日志显示级别
logging:
  level:
    com.wxy.rpc: info

# 配置 Thymeleaf 视图解析器
spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML
